-- Baseline schema, equivalent to what Hibernate generated from the entities before migrations
-- were introduced. Databases created that way are baselined at this version instead of re-running it.

CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(255) NOT NULL CONSTRAINT uq_app_user_username UNIQUE,
    email          VARCHAR(255) NOT NULL CONSTRAINT uq_app_user_email UNIQUE,
    password       VARCHAR(255) NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    enabled        BOOLEAN,
    account_locked BOOLEAN,
    created_date   VARCHAR(255) NOT NULL,
    updated_date   VARCHAR(255)
);

CREATE TABLE role (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) CONSTRAINT uq_role_name UNIQUE,
    created_date VARCHAR(255) NOT NULL,
    updated_date VARCHAR(255)
);

CREATE TABLE app_user_roles (
    users_id BIGINT NOT NULL CONSTRAINT fk_app_user_roles_user REFERENCES app_user (id),
    roles_id BIGINT NOT NULL CONSTRAINT fk_app_user_roles_role REFERENCES role (id)
);

CREATE TABLE token (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token        VARCHAR(255),
    created_at   TIMESTAMP(6),
    expires_at   TIMESTAMP(6),
    validated_at TIMESTAMP(6),
    user_id      BIGINT NOT NULL CONSTRAINT fk_token_user REFERENCES app_user (id)
);

CREATE TABLE category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL CONSTRAINT uq_category_name UNIQUE
);

CREATE TABLE product (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL CONSTRAINT uq_product_name UNIQUE,
    file_path         VARCHAR(255) NOT NULL CONSTRAINT uq_product_file_path UNIQUE,
    short_description VARCHAR(255) NOT NULL,
    long_description  VARCHAR(255) NOT NULL,
    brand             VARCHAR(255) NOT NULL,
    price             INTEGER      NOT NULL,
    category_id       BIGINT CONSTRAINT fk_product_category REFERENCES category (id)
);

CREATE TABLE inventory (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT  NOT NULL CONSTRAINT uq_inventory_product UNIQUE
                               CONSTRAINT fk_inventory_product REFERENCES product (id),
    quantity   INTEGER NOT NULL
);

CREATE TABLE address (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_line_1 VARCHAR(255) NOT NULL,
    address_line_2 VARCHAR(255),
    city           VARCHAR(255) NOT NULL,
    country        VARCHAR(255) NOT NULL,
    user_id        BIGINT       NOT NULL CONSTRAINT fk_address_user REFERENCES app_user (id)
);

CREATE TABLE web_order (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL CONSTRAINT fk_web_order_user REFERENCES app_user (id),
    address_id   BIGINT NOT NULL CONSTRAINT fk_web_order_address REFERENCES address (id),
    created_date VARCHAR(255),
    updated_date VARCHAR(255)
);

CREATE TABLE web_order_content (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT  NOT NULL CONSTRAINT fk_web_order_content_order REFERENCES web_order (id),
    product_id BIGINT  NOT NULL CONSTRAINT fk_web_order_content_product REFERENCES product (id),
    quantity   INTEGER NOT NULL
);

CREATE TABLE cta (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    source_info VARCHAR(255)
);
